name: build stuff

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: "Python 3.9 build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel

      - name: "Build and test"
        run: |
          set -xe
          make build-wheel
          pip install dist/*.whl
          pytest tests/
      - name: Archive dist package
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/
          retention-days: 14
  tests:
    name: "Python ${{ matrix.python-version }}"
    needs: build
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.5", "3.6", "3.7", "3.8", "3.9"]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Download build artifacts"
        uses: actions/download-artifact@v2
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          make tox-requirements
          pip install dist/*.whl
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: tox
