name: Release


on:
  release:
    types: [ released, prereleased]

jobs:
  bump2version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: install bump2version
      run: |
        pip install bump2version
    - name: bump
      run: |
        # from refs/tags/v1.2.3 get 1.2.3
        VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')
        echo $VERSION
        bump2version patch --verbose  --no-tag --new-version $VERSION

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update version
        branch: update_release_version
        base: master
        delete-branch: true
        title: 'Bump version to release'
        body: |
          Update master version to match release
          - bumped to release version

        labels: |
          automated pr
        reviewers: ibackus
        draft: false
